application: sweet-polls
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /styles
  static_dir: dist/mobile/dev/styles

- url: /scripts
  static_dir: dist/mobile/dev/scripts

- url: /fonts
  static_dir: dist/mobile/dev/fonts

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest